export const THEMES = {
  boca: {
    id: 'boca',
    club: 'Boca Juniors',
    stadium: 'La Bombonera',
    pano: 'assets/bombonera.jpg',
    panoVMin: 0.37,
    skyTop: '#2f78d4',
    skyHorizon: '#d4e8fb',
    fog: '#bcd6ef',
    grassA: '#48a33f',
    grassA2: '#43993a',
    grassB: '#3b8e35',
    grassB2: '#378730',
    track: null,
    ground: '#3a3f47',
    primary: '#0b3d91',
    secondary: '#ffc928',
    standColors: ['#0b3d91', '#ffc928'],
    crowd: ['#0b3d91', '#0b3d91', '#ffc928', '#1550b8', '#ffd94a', '#f4f4f4'],
    boards: ['BOCA JUNIORS', 'LA BOMBONERA', '¡DALE BOCA!', 'LA 12', 'XENEIZE', 'LA BOCA · 1905'],
    boardColors: [
      ['#0b3d91', '#ffc928'],
      ['#ffc928', '#0b3d91'],
    ],
    banner: { text: 'LA 12', bg: '#0b3d91', fg: '#ffc928', stripe: '#ffc928' },
    banner2: { text: 'DALE BOCA', bg: '#ffc928', fg: '#0b3d91', stripe: null },
    confetti: ['#0b3d91', '#ffc928', '#ffffff', '#ffc928'],
    sun: [7, 18, 9],
    sunColor: '#fff3dc',
    collectibleName: 'estrellas',
    cheers: ['¡DALE BOCA!', '¡GOLAZO!', '¡XENEIZE!', '¡LA 12!', '¡BOSTERO!'],
    deathWall: '¡Contra el alambrado!',
    deathSelf: '¡Te mordiste la cola!',
  },
  river: {
    id: 'river',
    club: 'River Plate',
    stadium: 'El Monumental',
    pano: 'assets/monumental.jpg',
    panoVMin: 0.33,
    skyTop: '#8fa8c0',
    skyHorizon: '#eef2f5',
    fog: '#dfe6ec',
    grassA: '#4aa443',
    grassA2: '#449b3d',
    grassB: '#3d9037',
    grassB2: '#398933',
    track: '#b0533f',
    ground: '#4a4a4f',
    primary: '#e1061e',
    secondary: '#ffffff',
    standColors: ['#f2f2f2', '#e1061e'],
    crowd: ['#ffffff', '#ffffff', '#e1061e', '#e1061e', '#f4f4f4', '#222222'],
    boards: ['RIVER PLATE', 'EL MONUMENTAL', '¡VAMOS RIVER!', 'MILLONARIO', 'NÚÑEZ · 1901', 'LA BANDA'],
    boardColors: [
      ['#e1061e', '#ffffff'],
      ['#ffffff', '#e1061e'],
    ],
    banner: { text: 'LOS BORRACHOS', bg: '#ffffff', fg: '#e1061e', stripe: null },
    banner2: { text: 'VAMOS RIVER', bg: '#e1061e', fg: '#ffffff', stripe: null },
    confetti: ['#ffffff', '#e1061e', '#ffffff', '#e1061e'],
    sun: [-8, 16, 7],
    sunColor: '#fbfbff',
    collectibleName: 'fantasmitas',
    cheers: ['¡VAMOS RIVER!', '¡BUUU!', '¡MILLONARIO!', '¡GOLAZO!', '¡FANTASMA!'],
    deathWall: '¡Contra el alambrado!',
    deathSelf: '¡Se hizo un nudo!',
  },
};
